### PR TITLE
Adds PR template to repo.

### PR DESCRIPTION
**Pull request by dbernstein**

### CODE REVIEW

**Comment by manez** [comment]
@dbernstein We need either an iCLA or a cCLA to cover any contribution to Islandora. We have a cCLA on file from LYRASIS - does that cover you at this point? 

Our list: https://github.com/Islandora/islandora/wiki/Contributor-License-Agreements

**Comment by whikloj** [comment]
Going on information that this work was done for Lyrasis and is as such covered under their cCLA.
See [IRC 2019-06-24@16:20 UTC](https://logs.woh.ca/islandora/2019-06-24)

**Review by whikloj — APPROVED** [review]

**Comment by whikloj** [comment]
Just realizing that I had a concern that you can't use the @Islandora-CLAW/committers tag in a different organization. If any Islandora 8 committers receive a notification from this, please respond otherwise we might need to use a team in this organization.

**Comment by whikloj** [comment]
No responses, so what if I use @Islandora-Devops/committers to ping the crew?

**Comment by seth-shaw-unlv** [comment]
I just got the notice.

**Comment by whikloj** [comment]
Right ok, @dbernstein thanks for opening all these PRs in Islandora-Devops. But could I get you to replace 
```
Tag (@ mention) interested parties or, if unsure, @Islandora-CLAW/committers
```
with
```
Tag (@ mention) interested parties or, if unsure, @Islandora-Devops/committers 
```

**Pull request merged**
